project:
  type: website
  output-dir: docs

website:
  title: "Heidi's BCB 520 Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/heidihosellmann/BCB520Portfolio
format:
  html:
    theme: cosmo
    css: styles.css



